function launch_terminal_in_file_location()
    local folder = vim.fn.expand('%:p:h')
    local enter_key = vim.api.nvim_replace_termcodes("<CR>", true, false, true)
    vim.cmd("sp")
    vim.cmd("te")
    vim.api.nvim_feedkeys("icd "..folder..enter_key, "i", true)
end
vim.keymap.set("n", "<leader>t", launch_terminal_in_file_location)
vim.keymap.set("n", "<leader>ev", function () vim.cmd("vsp ~/.config/nvim/") end)
vim.keymap.set("n", "<leader>a", function () vim.cmd("vsp"); vim.cmd("Alpha") end)
vim.keymap.set("n", "<C-h>", "<C-w>h:res<CR>")
vim.keymap.set("n", "<C-j>", "<C-w>j:res<CR>")
vim.keymap.set("n", "<C-k>", "<C-w>k:res<CR>")
vim.keymap.set("n", "<C-l>", "<C-w>l:res<CR>")
vim.keymap.set("t", "<leader><Esc>", "<C-\\><C-n>")

vim.keymap.set("v", "J", ":m '>+1<CR>gv=gv")
vim.keymap.set("v", "K", ":m '<-2<CR>gv=gv")
